name: google_tasks
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  gap: ^3.0.1
  go_router: ^13.2.0
  bloc: ^8.1.3
  equatable: ^2.0.5
  path_provider: ^2.1.2
  flutter_bloc: ^8.1.4
  hydrated_bloc: ^9.1.4
  firebase_core: ^2.25.4
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.20
  path: ^1.9.0
  sqlite3: ^2.4.0
  uuid: ^4.3.3
  json_annotation: ^4.8.1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  rxdart: ^0.27.7
  provider: ^6.1.2
  collection: ^1.18.0
  build: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  drift_dev: ^2.16.0
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.10

flutter:
  uses-material-design: true
