// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH0CvHxTT5MXBqnASsfi-V-XieDhsLwZU',
    appId: '1:64786816533:web:3936fda366ba57fa20f81c',
    messagingSenderId: '64786816533',
    projectId: 'tasks-copy',
    authDomain: 'tasks-copy.firebaseapp.com',
    storageBucket: 'tasks-copy.appspot.com',
    measurementId: 'G-1KE6BEC87Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-5RFNCJXImwwA5gXABby5x1lTsSAjsTE',
    appId: '1:64786816533:android:bda88694c56a77d620f81c',
    messagingSenderId: '64786816533',
    projectId: 'tasks-copy',
    storageBucket: 'tasks-copy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWQDxjh2Fco3lt4dBRlX9AlXR3rH9XBp0',
    appId: '1:64786816533:ios:e6cf2bc7a55e18a820f81c',
    messagingSenderId: '64786816533',
    projectId: 'tasks-copy',
    storageBucket: 'tasks-copy.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWQDxjh2Fco3lt4dBRlX9AlXR3rH9XBp0',
    appId: '1:64786816533:ios:e6cf2bc7a55e18a820f81c',
    messagingSenderId: '64786816533',
    projectId: 'tasks-copy',
    storageBucket: 'tasks-copy.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH0CvHxTT5MXBqnASsfi-V-XieDhsLwZU',
    appId: '1:64786816533:web:96b8cfee272c0fdc20f81c',
    messagingSenderId: '64786816533',
    projectId: 'tasks-copy',
    authDomain: 'tasks-copy.firebaseapp.com',
    storageBucket: 'tasks-copy.appspot.com',
    measurementId: 'G-DH9RSNWTTL',
  );
}
